# -*- coding: utf-8 -*-
"""IDS_20200313_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l43kM02_Vr8-HUlJTvO6xPAfFQFz7IXt
"""

# hello.py
print("Hello World!")

# zen.py
import this